/*
** Pokemon Primal
** File description:
** Engine
*/

#pragma once
#include <string>
#include <Pokemon/PokemonType.hpp>
#include <unordered_map>

// tables are for defense

static std::unordered_map<Type, float> typeTableNormal = {
    {Type::NORMAL, 1.0},
    {Type::FIRE, 1.0},
    {Type::WATER, 1.0},
    {Type::ELECTRIC, 1.0},
    {Type::GRASS, 1.0},
    {Type::ICE, 1.0},
    {Type::FIGHTING, 2.0},
    {Type::POISON, 1.0},
    {Type::GROUND, 1.0},
    {Type::FLYING, 1.0},
    {Type::PSYCHIC, 1.0},
    {Type::BUG, 1.0},
    {Type::ROCK, 1.0},
    {Type::GHOST, 0.0},
    {Type::DRAGON, 1.0},
    {Type::DARK, 1.0},
    {Type::STEEL, 1.0},
    {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableFire = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 0.5},
        {Type::WATER, 2.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 0.5},
        {Type::ICE, 0.5},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 2.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 0.5},
        {Type::ROCK, 2.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 0.5},
        {Type::FAIRY, 0.5}
};
static std::unordered_map<Type, float> typeTableWater = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 0.5},
        {Type::WATER, 0.5},
        {Type::ELECTRIC, 2.0},
        {Type::GRASS, 2.0},
        {Type::ICE, 0.5},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 0.5},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableElectric = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 0.5},
        {Type::GRASS, 1.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 2.0},
        {Type::FLYING, 0.5},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 0.5},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableGrass = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 2.0},
        {Type::WATER, 0.5},
        {Type::ELECTRIC, 0.5},
        {Type::GRASS, 0.5},
        {Type::ICE, 2.0},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 2.0},
        {Type::GROUND, 0.5},
        {Type::FLYING, 2.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 2.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 0.5},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableIce = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 2.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 1.0},
        {Type::ICE, 0.5},
        {Type::FIGHTING, 2.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 2.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 2.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableFighting = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 1.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 2.0},
        {Type::PSYCHIC, 2.0},
        {Type::BUG, 0.5},
        {Type::ROCK, 0.5},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 0.5},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 2.0}
};
static std::unordered_map<Type, float> typeTablePoison = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 0.5},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 0.5},
        {Type::POISON, 0.5},
        {Type::GROUND, 2.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 2.0},
        {Type::BUG, 0.5},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 0.5}
};
static std::unordered_map<Type, float> typeTableGround = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 2.0},
        {Type::ELECTRIC, 0.0},
        {Type::GRASS, 2.0},
        {Type::ICE, 2.0},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 0.5},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 0.5},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableFlying = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 2.0},
        {Type::GRASS, 0.5},
        {Type::ICE, 2.0},
        {Type::FIGHTING, 0.5},
        {Type::POISON, 1.0},
        {Type::GROUND, 0.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 0.5},
        {Type::ROCK, 2.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTablePsychic = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 1.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 0.5},
        {Type::POISON, 1.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 0.5},
        {Type::BUG, 2.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 2.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 2.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableBug = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 2.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 0.5},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 0.5},
        {Type::POISON, 1.0},
        {Type::GROUND, 0.5},
        {Type::FLYING, 2.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 2.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableRock = {
        {Type::NORMAL, 0.5},
        {Type::FIRE, 0.5},
        {Type::WATER, 2.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 2.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 2.0},
        {Type::POISON, 0.5},
        {Type::GROUND, 2.0},
        {Type::FLYING, 0.5},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 2.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableGhost = {
        {Type::NORMAL, 0.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 1.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 0.0},
        {Type::POISON, 0.5},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 0.5},
        {Type::ROCK, 1.0},
        {Type::GHOST, 2.0},
        {Type::DRAGON, 1.0},
        {Type::DARK, 2.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 1.0}
};
static std::unordered_map<Type, float> typeTableDragon = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 0.5},
        {Type::WATER, 0.5},
        {Type::ELECTRIC, 0.5},
        {Type::GRASS, 0.5},
        {Type::ICE, 2.0},
        {Type::FIGHTING, 1.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 1.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 2.0},
        {Type::DARK, 1.0},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 2.0}
};
static std::unordered_map<Type, float> typeTableDark = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 1.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 2.0},
        {Type::POISON, 1.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 0.0},
        {Type::BUG, 2.0},
        {Type::ROCK, 1.0},
        {Type::GHOST, 0.5},
        {Type::DRAGON, 1.0},
        {Type::DARK, 0.5},
        {Type::STEEL, 1.0},
        {Type::FAIRY, 2.0}
};
static std::unordered_map<Type, float> typeTableSteel = {
        {Type::NORMAL, 0.5},
        {Type::FIRE, 2.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 0.5},
        {Type::ICE, 0.5},
        {Type::FIGHTING, 2.0},
        {Type::POISON, 0.0},
        {Type::GROUND, 2.0},
        {Type::FLYING, 0.5},
        {Type::PSYCHIC, 0.5},
        {Type::BUG, 0.5},
        {Type::ROCK, 0.5},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 0.5},
        {Type::DARK, 1.0},
        {Type::STEEL, 0.5},
        {Type::FAIRY, 0.5}
};
static std::unordered_map<Type, float> typeTableFairy = {
        {Type::NORMAL, 1.0},
        {Type::FIRE, 1.0},
        {Type::WATER, 1.0},
        {Type::ELECTRIC, 1.0},
        {Type::GRASS, 1.0},
        {Type::ICE, 1.0},
        {Type::FIGHTING, 0.5},
        {Type::POISON, 2.0},
        {Type::GROUND, 1.0},
        {Type::FLYING, 1.0},
        {Type::PSYCHIC, 1.0},
        {Type::BUG, 0.5},
        {Type::ROCK, 1.0},
        {Type::GHOST, 1.0},
        {Type::DRAGON, 0.0},
        {Type::DARK, 0.5},
        {Type::STEEL, 2.0},
        {Type::FAIRY, 1.0}
};

static std::unordered_map<Type, std::unordered_map<Type, float>> typeTable = {
        {Type::NORMAL, typeTableNormal},
        {Type::FIRE, typeTableFire},
        {Type::WATER, typeTableWater},
        {Type::ELECTRIC, typeTableElectric},
        {Type::GRASS, typeTableGrass},
        {Type::ICE, typeTableIce},
        {Type::FIGHTING, typeTableFighting},
        {Type::POISON, typeTablePoison},
        {Type::GROUND, typeTableGround},
        {Type::FLYING, typeTableFlying},
        {Type::PSYCHIC, typeTablePsychic},
        {Type::BUG, typeTableBug},
        {Type::ROCK, typeTableRock},
        {Type::GHOST, typeTableGhost},
        {Type::DRAGON, typeTableDragon},
        {Type::DARK, typeTableDark},
        {Type::STEEL, typeTableSteel},
        {Type::FAIRY, typeTableFairy}
};







